In [2]:
from IPython.display import HTML

HTML('''<script>
code_show=true; 
function code_toggle() {
 if (code_show){
 $('div.input').hide();
 } else {
 $('div.input').show();
 }
 code_show = !code_show
} 
$( document ).ready(code_toggle);
</script>
<form action="javascript:code_toggle()"><input type="submit" value="Click here to toggle on/off the raw code."></form>''')

<h1>Interactive Session for Evaluating Graphs</h1>

In [9]:
import tensorflow as tf
from IPython.display import display

sess1 = tf.InteractiveSession()

input = tf.Variable([[[1, 1, 1], [2, 2, 2]],
                    [[3, 3, 3], [4, 4, 4]],
                    [[5, 5, 5], [6, 6, 6]]])


input.initializer.run()
p1 = tf.pow(input,3)
print(p1.eval())


[[[  1   1   1]
  [  8   8   8]]

 [[ 27  27  27]
  [ 64  64  64]]

 [[125 125 125]
  [216 216 216]]]


<h1>Regular Session for evaluating Graphs</h1>

In [7]:
import tensorflow as tf
from IPython.display import display

input = tf.Variable([[[1, 1, 1], [2, 2, 2]],
                    [[3, 3, 3], [4, 4, 4]],
                    [[5, 5, 5], [6, 6, 6]]])

with tf.Session() as sess2:
    init_op = tf.global_variables_initializer()
    sess2.run(init_op)
    p2 = tf.pow(input,3)
    print(sess2.run(p2))

[[[  1   1   1]
  [  8   8   8]]

 [[ 27  27  27]
  [ 64  64  64]]

 [[125 125 125]
  [216 216 216]]]


<h1>tf.strided_slice()</h1>

In [2]:

import tensorflow as tf
from IPython.display import display

sess1 = tf.InteractiveSession()

input = tf.Variable([[[1, 1, 1], [2, 2, 2]],
                    [[3, 3, 3], [4, 4, 4]],
                    [[5, 5, 5], [6, 6, 6]]])
input.initializer.run()
print('Input is -')
print(input.eval())
w = tf.strided_slice(input,[1,0,0],[2,1,3],[1,1,1])
print('\nOuput is -')
print(w.eval())

Input is -
[[[1 1 1]
  [2 2 2]]

 [[3 3 3]
  [4 4 4]]

 [[5 5 5]
  [6 6 6]]]

Ouput is -
[[[3 3 3]]]
